In [1]:
%matplotlib widget
from matplotlib import pyplot as plt

In [2]:
import sys
import pandas as pd
import numpy as np
import IPython
import scipy as sp
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import mglearn
from sklearn.datasets import make_blobs

In [3]:
x = np.linspace(-10, 10, 100)
y = np.sin(x)
plt.plot(x, y, marker='x')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [4]:
# The object returned by load_iris is a BUNCH object and is very similar to a dictionary.
iris_dataset = load_iris()

In [5]:
print("The keys of the iris datasets: \n{}".format(iris_dataset.keys()))

The keys of the iris datasets: 
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [6]:
# TARGET AND TARGET_NAME ARE TWO DIMENSTIONAL NUMPY ARRAY, WHILE DATA IS A ONE-DIMENSIONAL 
# NUMPY ARRAY
print(iris_dataset["data"][:5], "\n")
print(list(iris_dataset["target_names"][x] for x in iris_dataset["target"][:5]), "\n")
print(iris_dataset["target_names"])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]] 

['setosa', 'setosa', 'setosa', 'setosa', 'setosa'] 

['setosa' 'versicolor' 'virginica']


In [7]:
X_train, X_test, y_train, y_test = \
train_test_split(iris_dataset['data'], iris_dataset['target'], random_state=0)

In [8]:
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(112, 4) (112,) (38, 4) (38,)


In [16]:
iris_dataframe = pd.DataFrame(X_train, columns=iris_dataset.feature_names, index=[x+1 for x in range(112)])
iris_dataframe

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
1                  5.9               3.0                4.2               1.5
2                  5.8               2.6                4.0               1.2
3                  6.8               3.0                5.5               2.1
4                  4.7               3.2                1.3               0.2
5                  6.9               3.1                5.1               2.3
..                 ...               ...                ...               ...
108                4.9               3.1                1.5               0.1
109                6.3               2.9                5.6               1.8
110                5.8               2.7                4.1               1.0
111                7.7               3.8                6.7               2.2
112                4.6               3.2                1.4               0.2

[112 rows x 4 columns]

In [17]:
grr = pd.plotting.scatter_matrix(iris_dataframe, c=y_train, figsize=(15 ,15), marker='o', hist_kwds={'bins':20}, s=60, alpha=.8, cmap=mglearn.cm3)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [22]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [21]:
# Testing our model on a new set of data, but we don't know the accuracy of this prediction, so we'll use our testing data set!
X_new = np.array([[5,2.9,1,0.2]])
prediction = knn.predict(X_new)
print("Prediction: {}".format(iris_dataset["target_names"][prediction]))

Prediction: ['setosa']


In [23]:
y_prediction = knn.predict(X_test)
print("The prediction for y:\n{}".format(y_prediction))
print("The actual values for y:\n{}".format(y_test))

The prediction for y:
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]
The actual values for y:
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1]


In [25]:
print("Test set score {:.2f}".format(np.mean(y_prediction == y_test)))
print("Test set score {:.2f}".format(knn.score(X_test, y_test)))

Test set score 0.97
Test set score 0.97


## Chapter 2

### Supervised ML Algorithms.

In [35]:
%matplotlib widget
# generating the dataset
X, y = mglearn.datasets.make_forge()
# plotting it
print(X)
print("\n", y)
mglearn.discrete_scatter(X[:, 0], X[:, 1], y)
plt.legend(["Class 0", "Class 1"], loc=4)
plt.xlabel("First feature")
plt.ylabel("Second feature")

[[ 9.96346605  4.59676542]
 [11.0329545  -0.16816717]
 [11.54155807  5.21116083]
 [ 8.69289001  1.54322016]
 [ 8.1062269   4.28695977]
 [ 8.30988863  4.80623966]
 [11.93027136  4.64866327]
 [ 9.67284681 -0.20283165]
 [ 8.34810316  5.13415623]
 [ 8.67494727  4.47573059]
 [ 9.17748385  5.09283177]
 [10.24028948  2.45544401]
 [ 8.68937095  1.48709629]
 [ 8.92229526 -0.63993225]
 [ 9.49123469  4.33224792]
 [ 9.25694192  5.13284858]
 [ 7.99815287  4.8525051 ]
 [ 8.18378052  1.29564214]
 [ 8.7337095   2.49162431]
 [ 9.32298256  5.09840649]
 [10.06393839  0.99078055]
 [ 9.50048972 -0.26430318]
 [ 8.34468785  1.63824349]
 [ 9.50169345  1.93824624]
 [ 9.15072323  5.49832246]
 [11.563957    1.3389402 ]]

 [1 0 1 0 0 1 1 0 1 1 1 1 0 0 1 1 1 0 0 1 0 0 0 0 1 0]


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Text(0, 0.5, 'Second feature')

In [37]:
# Regression example
%matplotlib widget
X, y = mglearn.datasets.make_wave(n_samples=40)
plt.plot(X, y, 'o')
plt.ylim(-3, 3)
plt.xlabel("Feature")
plt.ylabel("Target")

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Text(0, 0.5, 'Target')

## Real world example.

### First Example: Classification example.

In [40]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()
print("cancer.keys():\n {}".format(cancer.keys()))

print("Sample counts per class:\n{}".\
      format({u: v for u, v in zip(cancer.target_names, np.bincount(cancer.target))}))

cancer.keys():
 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])
Sample counts per class:
{'malignant': 212, 'benign': 357}


### 2nd Example: regression example.

In [139]:
from sklearn.datasets import load_boston
boston = load_boston()
print(boston.keys())
print("Data shape:\n{}".format(boston.data.shape))

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])
Data shape:
(506, 13)


In [48]:
X, y = mglearn.datasets.load_extended_boston()
print(X.shape)

(506, 104)


In [71]:
X, y = mglearn.datasets.make_forge()
# Dividing it into a portion for training, a portion for testing.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

clf = KNeighborsClassifier(n_neighbors=3)
clf.fit(X_train, y_train)

# Printing the prediction
y_predict = clf.predict(X_test)
print("The prediction:{}".format(y_predict))
print("The real data output:{}".format(y_test))

print("The accuracy = {:.2f}".format(clf.score(X_test, y_test), 2))
print("The accuracy = {:.2f}".format(np.mean(y_predict == y_test)))

The prediction:[1 0 1 0 1 0 0]
The real data output:[1 0 1 0 1 1 0]
The accuracy = 0.86
The accuracy = 0.86


/home/yusuf/anaconda3/lib/python3.8/site-packages/sklearn/utils/deprecation.py:86: FutureWarning: Function make_blobs is deprecated; Please import make_blobs directly from scikit-learn
  warnings.warn(msg, category=FutureWarning)


#### Showing the decision boundary differences for using different number of neighbors.

In [74]:
fig, axes = plt.subplots(1, 3, figsize=(10, 3))

for n_neighbors, ax in zip([1, 3, 9], axes):
    clf = KNeighborsClassifier(n_neighbors=n_neighbors).fit(X, y)
    mglearn.plots.plot_2d_separator(clf, X, fill=True, eps=0.5, ax=ax, alpha=.4)
    mglearn.discrete_scatter(X[:, 0], X[:, 1], y, ax=ax)
    ax.set_title("{} neighbor(s)".format(n_neighbors))
    ax.set_xlabel("feature 0")
    ax.set_ylabel("feature 1")
axes[0].legend(loc=3)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [99]:
%matplotlib widget
mglearn.plots.plot_knn_classification(n_neighbors=1)

/home/yusuf/anaconda3/lib/python3.8/site-packages/sklearn/utils/deprecation.py:86: FutureWarning: Function make_blobs is deprecated; Please import make_blobs directly from scikit-learn
  warnings.warn(msg, category=FutureWarning)


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [93]:
# Working on classification dataset
%matplotlib widget
X_train, X_test, y_train, y_test = train_test_split(cancer.data, cancer.target, stratify=cancer.target, random_state=66)
training_accuracy = []
test_accuracy = []
neighbors_settings = range(1, 11)


for n_neighbor in neighbors_settings:
    
    clf = KNeighborsClassifier(n_neighbors=n_neighbor)
    clf.fit(X_train, y_train)
    training_accuracy.append(clf.score(X_train, y_train))
    test_accuracy.append(round(clf.score(X_test, y_test), 2))
    print("The accuracy for {} number of neighbors = {:.2f} %".format(n_neighbor, clf.score(X_test, y_test) * 100))


plt.plot(neighbors_settings, training_accuracy, label="trainging accuracy")
plt.plot(neighbors_settings, test_accuracy, label="test accuracy", marker='x')
plt.ylabel("Accuracy")
plt.ylim(0.88, 1.00)
plt.xlabel("Neighbours settings")
plt.legend()

## The left side of the plot is where the model is complex, and is where overfitting happens
## The right side of the plot is where the model is so simple, and is where underfitting happens

The accuracy for 1 number of neighbors = 90.21 %
The accuracy for 2 number of neighbors = 88.81 %
The accuracy for 3 number of neighbors = 92.31 %
The accuracy for 4 number of neighbors = 92.31 %
The accuracy for 5 number of neighbors = 92.31 %
The accuracy for 6 number of neighbors = 93.71 %
The accuracy for 7 number of neighbors = 93.01 %
The accuracy for 8 number of neighbors = 93.01 %
The accuracy for 9 number of neighbors = 91.61 %
The accuracy for 10 number of neighbors = 91.61 %


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [104]:
# Predictions made by three-nearest-neighbors regression on the wave dataset%matplotlib widget
mglearn.plots.plot_knn_regression(n_neighbors=3)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [109]:
from sklearn.neighbors import KNeighborsRegressor

X, y = mglearn.datasets.make_wave(n_samples=40)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

reg = KNeighborsRegressor(n_neighbors=3)
reg.fit(X_train, y_train)

print("Test set prediction: {}\n".format(reg.predict(X_test)))

# Value 1 of R^2 indicates a perfect prediction, while value 0 corresponds to a constant model that just predicts the mean of the training set responses.
print("Test set prediction accuracy (R^2) aka the coefficient of determination: {:.3f}\n".format(reg.score(X_test, y_test)))



Test set prediction: [-0.05396539  0.35686046  1.13671923 -1.89415682 -1.13881398 -1.63113382
  0.35686046  0.91241374 -0.44680446 -1.13881398]

Test set prediction accuracy (R^2) aka the coefficient of determination: 0.834



In [116]:
fig, axes = plt.subplots(1, 3, figsize=(15 ,4))
line = np.linspace(-3, 3, 1000).reshape(-1, 1)

for n_neighbors, ax in zip([1, 3, 9], axes):
    
    reg = KNeighborsRegressor(n_neighbors=n_neighbors)
    reg.fit(X_train, y_train)
    ax.plot(line, reg.predict(line))
    ax.plot(X_train, y_train, "o", c=mglearn.cm2(0), markersize=8)
    ax.plot(X_test, y_test, "v", c=mglearn.cm2(1), markersize=8)
    
    ax.set_title("{}, test score: {:.2f}, training score: {:.2f}\n".format(n_neighbors, reg.score(X_test, y_test), reg.score(X_train, y_train)))
    ax.set_xlabel("Feature")
    ax.set_ylabel("Target")
    axes[0].legend(["Model prediction", "Training data/target", "Test data/target"], loc="best")

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …